version: '3.8'
services:
  demo-app:
    image: busybox
    command: >
      sh -c 'while true; do echo "<13>1 $(date -u +"%Y-%m-%dT%H:%M:%SZ") demo-app demo-app - - - This is a syslog demo log message from demo-app" | nc alloy 51893; sleep 2; done'
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - LOKI_API_TOKEN
    ports:
      - "51893:51893" # syslog TCP
      - "51898:51898" # syslog UDP
    entrypoint: ["/bin/alloy", "run", "/etc/alloy/config.alloy"]
    depends_on:
      - demo-app
